# Generated by Django 5.1 on 2024-08-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="products",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_products",
                to="network.product",
                verbose_name="Продукты",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_products_set",
                to="network.product",
                verbose_name="Сеть",
            ),
        ),
    ]
