# Generated by Django 5.1 on 2024-08-17 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_network_products_alter_product_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="network",
            name="products",
        ),
        migrations.AlterField(
            model_name="product",
            name="network",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_products_set",
                to="network.network",
                verbose_name="Сеть",
            ),
        ),
    ]
